### ISSUE TITLE
'xmlns' came as a complete surprise to me

### ISSUE THREAD

**Issue by jlerbsc** [antlr/stringtemplate4#166]
We have this error message "'xmlns' came as a complete surprise to me" if we declare a namespace in html tag for exemple:

     <html xmlns="http://www.w3.org/1999/xhtml">

**Comment by jeff5** [comment]
I guess your template is HTML. The problem is likely to be that you are not using, or not telling StringTempate that you are using, something other than "<" and ">" to delimit your template expressions. See what is said about HTML here:
https://github.com/antlr/stringtemplate4/blob/master/doc/introduction.md#accessing-properties-of-model-objects
and here:
https://github.com/antlr/stringtemplate4/blob/master/doc/templates.md#templates
In the first, particularly, you see how in Java the ST constructor is given the delimiters.

Delimiters may also be specified in a template group file:
https://github.com/antlr/stringtemplate4/blob/master/doc/groups.md#setting-template-expression-delimiters

**Comment by jlerbsc** [comment]
It's right! Thanks.

**Comment by jeff5** [comment]
You're welcome. @sharwell or @parrt to close? And #165 I guess has its origin in the same error.

**Comment by jlerbsc** [comment]
You are rigth too. Thanks
