### ISSUE TITLE
Support Iterable<T>

### ISSUE THREAD

**Issue by sharwell** [antlr/stringtemplate4#79]
Currently the interpreter supports `Collection<T>` and `Iterator<T>`, but it does not support `Iterable<T>`.

**Comment by kakawait** [comment]
@sharwell I'd like just to warn you that with this new change there is a regression when using `com.fasterxml.jackson.databind.JsonNode`
Before `4.1` (tested on `4.0.8`) `JsonNode` does not match `Collection` so object itself was returned and `writePOJO` was used.
Since `4.1` (until `4.3`) `JsonNode` matches `Iterable` but `TextNode` (mostly children of `JsonNode`). However `TextNode` iterator is empty...

At the end, inside template rendering `JsonNode` will be empty.

I don't think is `ST4` fault is more conflict with `Jackson Databind` vision. But could be valuable to add note for people migrating from `4.0.8` to >= `4.1`

Basic workaround is to use `.toString()` from `JsonNode` and pass `String` value to `st`
